# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sello' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'


  platform :ios, '11.4'
  # Pods for Sello

  target 'SelloTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SelloUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
